<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!--Naming conventions here: https://manual.macromates.com/en/language_grammars#naming_conventions-->
<dict>
	<key>fileTypes</key>
	<array>
		<string>al</string>
		<string>dal</string>
	</array>
	<key>injectionSelector</key>
	<string>L:source.al</string>
	<key>name</key>
	<string>ALtoolbox</string>
	<key>patterns</key>
	<array>
		<dict> 
			<key>match</key> 
			<string>^\s*//\s*#region\b</string> 
			<key>name</key> 
			<string>keyword.operators.al</string> 
		</dict> 
		<dict> 
			<key>match</key> 
			<string>^\s*//\s*#endregion\b</string> 
			<key>name</key> 
			<string>keyword.operators.al</string> 
		</dict> 
	</array>
	<key>scopeName</key>
	<string>al.toolbox</string>
</dict>
</plist>
